openapi: 3.0.3
info:
  version: 1.0.0
  title: Proxy-manager
  description: Менеджер прокси-соединений команды DE

components:
  schemas:
    StatusResponse:
      type: object
      properties:
        status:
          type: string

  responses:
    200:
      description: "Ok"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StatusResponse"
